# Generated by Django 3.2.13 on 2022-09-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimCategorie',
            fields=[
                ('categorieid', models.IntegerField(db_column='CategorieID', primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, db_column='Label', max_length=9, null=True)),
                ('titre', models.CharField(blank=True, db_column='Titre', max_length=1, null=True)),
            ],
            options={
                'db_table': 'Dim_Categorie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimDate',
            fields=[
                ('dateid', models.IntegerField(db_column='DateID', primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('code', models.IntegerField()),
            ],
            options={
                'db_table': 'Dim_Date',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimEmployee',
            fields=[
                ('id_employee', models.IntegerField(db_column='ID_Employee', primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, db_column='Nom', max_length=255, null=True)),
                ('prenom', models.CharField(blank=True, db_column='Prenom', max_length=255, null=True)),
                ('sexe', models.CharField(blank=True, db_column='Sexe', max_length=1, null=True)),
                ('datenaissance', models.DateField(blank=True, db_column='DateNaissance', null=True)),
                ('lieunaissance', models.CharField(blank=True, db_column='LieuNaissance', max_length=16, null=True)),
                ('adresse', models.CharField(blank=True, db_column='Adresse', max_length=255, null=True)),
                ('ville', models.CharField(blank=True, db_column='Ville', max_length=255, null=True)),
                ('codepostal', models.IntegerField(blank=True, db_column='CodePostal', null=True)),
                ('nbenfant', models.IntegerField(blank=True, db_column='NbEnfant', null=True)),
                ('salairebase', models.FloatField(blank=True, db_column='SalaireBase', null=True)),
                ('banque', models.CharField(blank=True, db_column='Banque', max_length=50, null=True)),
                ('daterecrutement', models.DateField(blank=True, db_column='DateRecrutement', null=True)),
                ('datedebutcontrat', models.DateField(blank=True, db_column='DateDebutContrat', null=True)),
                ('dureecontrat', models.IntegerField(blank=True, db_column='DureeContrat', null=True)),
                ('poste', models.CharField(blank=True, db_column='Poste', max_length=12, null=True)),
                ('montantrend', models.FloatField(blank=True, db_column='MontantRend', null=True)),
                ('noteabsence', models.FloatField(blank=True, db_column='NoteAbsence', null=True)),
                ('nbrabsence', models.IntegerField(blank=True, db_column='NbrAbsence', null=True)),
                ('noteassiduite', models.FloatField(blank=True, db_column='NoteAssiduite', null=True)),
                ('titre', models.CharField(blank=True, db_column='Titre', max_length=1, null=True)),
                ('quitter', models.CharField(blank=True, db_column='Quitter', max_length=1, null=True)),
                ('datequitter', models.DateField(blank=True, db_column='DateQuitter', null=True)),
                ('motifquitter', models.CharField(blank=True, db_column='MotifQuitter', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Dim_Employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimEtatcivil',
            fields=[
                ('id_etatcivil', models.IntegerField(db_column='ID_EtatCivil', primary_key=True, serialize=False)),
                ('label', models.CharField(db_column='Label', max_length=11)),
            ],
            options={
                'db_table': 'Dim_EtatCivil',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimFonction',
            fields=[
                ('id_fonction', models.IntegerField(db_column='ID_Fonction', primary_key=True, serialize=False)),
                ('label', models.CharField(db_column='Label', max_length=38)),
            ],
            options={
                'db_table': 'Dim_Fonction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimJours',
            fields=[
                ('field_id', models.IntegerField(db_column='_ID', primary_key=True, serialize=False)),
                ('jour', models.CharField(blank=True, db_column='Jour', max_length=12, null=True)),
            ],
            options={
                'db_table': 'Dim_Jours',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimModepaiement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_modepaiement', models.IntegerField(blank=True, db_column='ID_ModePaiement', null=True)),
                ('label', models.CharField(blank=True, db_column='Label', max_length=8, null=True)),
            ],
            options={
                'db_table': 'Dim_ModePaiement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimMois',
            fields=[
                ('field_id_mois', models.IntegerField(db_column='_ID_Mois', primary_key=True, serialize=False)),
                ('mois', models.CharField(blank=True, db_column='Mois', max_length=11, null=True)),
                ('annee', models.IntegerField(blank=True, db_column='Annee', null=True)),
            ],
            options={
                'db_table': 'Dim_Mois',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimMotifconge',
            fields=[
                ('id_motifconge', models.IntegerField(db_column='ID_MotifConge', primary_key=True, serialize=False)),
                ('motif', models.CharField(blank=True, db_column='Motif', max_length=27, null=True)),
            ],
            options={
                'db_table': 'Dim_MotifConge',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimService',
            fields=[
                ('serviceid', models.IntegerField(db_column='ServiceID', primary_key=True, serialize=False)),
                ('label', models.CharField(db_column='Label', max_length=12)),
            ],
            options={
                'db_table': 'Dim_Service',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimTypeconge',
            fields=[
                ('id_typeconge', models.IntegerField(db_column='ID_TypeConge', primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, db_column='Label', max_length=22, null=True)),
                ('paye', models.CharField(blank=True, db_column='Paye', max_length=1, null=True)),
            ],
            options={
                'db_table': 'Dim_TypeConge',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimTypecontrat',
            fields=[
                ('typecontratid', models.IntegerField(db_column='TypeContratID', primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, db_column='LABEL', max_length=31, null=True)),
            ],
            options={
                'db_table': 'Dim_TypeContrat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimTypesalaire',
            fields=[
                ('id_typesalaire', models.IntegerField(db_column='ID_TypeSalaire', primary_key=True, serialize=False)),
                ('label', models.CharField(db_column='Label', max_length=13)),
            ],
            options={
                'db_table': 'Dim_TypeSalaire',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactConge',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('id_employee', models.IntegerField(db_column='ID_Employee')),
                ('id_motifconge', models.IntegerField(db_column='ID_MotifConge')),
                ('id_typeconge', models.IntegerField(db_column='ID_TypeConge')),
                ('id_datedebut', models.IntegerField(db_column='ID_DateDebut')),
                ('id_jourdebut', models.IntegerField(db_column='ID_JourDebut')),
                ('id_jourfin', models.IntegerField(db_column='ID_JourFin')),
                ('nbjourabsent', models.FloatField(blank=True, db_column='NbJourAbsent', null=True)),
                ('nbheureservice', models.FloatField(blank=True, db_column='NbHeureService', null=True)),
            ],
            options={
                'db_table': 'Fact_Conge',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactSalaire',
            fields=[
                ('id_salaire', models.IntegerField(db_column='ID_Salaire', primary_key=True, serialize=False)),
                ('id_employee', models.IntegerField(db_column='ID_Employee')),
                ('id_typesalaire', models.IntegerField(db_column='ID_TypeSalaire')),
                ('id_modepaiement', models.IntegerField(db_column='ID_ModePaiement')),
                ('typecontratid', models.IntegerField(db_column='TypeContratID')),
                ('serviceid', models.IntegerField(db_column='ServiceID')),
                ('id_fonction', models.IntegerField(db_column='ID_Fonction')),
                ('id_etatcivil', models.IntegerField(db_column='ID_EtatCivil')),
                ('categorieid', models.IntegerField(db_column='CategorieID')),
                ('id_mois', models.IntegerField(db_column='ID_Mois')),
                ('noteprime', models.FloatField(blank=True, db_column='NotePrime', null=True)),
                ('retenueimpot', models.FloatField(blank=True, db_column='RetenueImpot', null=True)),
                ('retenuecnss', models.FloatField(blank=True, db_column='RetenueCNSS', null=True)),
                ('retenuetotal', models.FloatField(blank=True, db_column='RetenueTotal', null=True)),
                ('primelogement', models.FloatField(blank=True, db_column='PrimeLogement', null=True)),
                ('indicevestimentaire', models.FloatField(blank=True, db_column='IndiceVestimentaire', null=True)),
                ('primetransport', models.FloatField(blank=True, db_column='PrimeTransport', null=True)),
                ('primepresence', models.FloatField(blank=True, db_column='PrimePresence', null=True)),
                ('primeresponsabilite', models.FloatField(blank=True, db_column='PrimeResponsabilite', null=True)),
                ('primedeplacement', models.FloatField(blank=True, db_column='PrimeDeplacement', null=True)),
                ('indemniterisque', models.FloatField(blank=True, db_column='IndemniteRisque', null=True)),
                ('primeexceptionnelle', models.FloatField(blank=True, db_column='PrimeExceptionnelle', null=True)),
                ('indemnitedifferentielle', models.FloatField(blank=True, db_column='IndemniteDifferentielle', null=True)),
                ('primeastreint', models.FloatField(blank=True, db_column='PrimeAstreint', null=True)),
                ('primekilometrique', models.FloatField(blank=True, db_column='PrimeKilometrique', null=True)),
                ('indemnitepanier', models.FloatField(blank=True, db_column='IndemnitePanier', null=True)),
                ('indemnitepanier2', models.FloatField(blank=True, db_column='IndemnitePanier2', null=True)),
                ('indemniteaidkbir', models.FloatField(blank=True, db_column='IndemniteAidKbir', null=True)),
                ('rappeltransport', models.FloatField(blank=True, db_column='RappelTransport', null=True)),
                ('rappelreclassement', models.FloatField(blank=True, db_column='RappelReclassement', null=True)),
                ('primeexceptionnel', models.FloatField(blank=True, db_column='PrimeExceptionnel', null=True)),
                ('rappelmoisoctobre', models.FloatField(blank=True, db_column='RappelMoisOctobre', null=True)),
                ('primebilan2012', models.FloatField(blank=True, db_column='PrimeBilan2012', null=True)),
                ('correctionindemnite', models.FloatField(blank=True, db_column='CorrectionIndemnite', null=True)),
                ('primetotal', models.FloatField(blank=True, db_column='PrimeTotal', null=True)),
                ('salairebrut', models.FloatField(blank=True, db_column='SalaireBrut', null=True)),
                ('salairenet', models.FloatField(blank=True, db_column='SalaireNet', null=True)),
                ('salairenetservi', models.FloatField(blank=True, db_column='SalaireNetServi', null=True)),
                ('salaireimposable', models.FloatField(blank=True, db_column='SalaireImposable', null=True)),
                ('salairenetrecu', models.FloatField(blank=True, db_column='SalaireNetRecu', null=True)),
                ('soldepret', models.FloatField(blank=True, db_column='SoldePret', null=True)),
                ('eretenuecnss', models.FloatField(blank=True, db_column='ERetenueCNSS', null=True)),
                ('eaccidenttravail', models.FloatField(blank=True, db_column='EAccidentTravail', null=True)),
                ('brutsociete', models.FloatField(blank=True, db_column='BrutSociete', null=True)),
                ('brutetindemnite', models.FloatField(blank=True, db_column='BrutEtIndemnite', null=True)),
                ('brutprime', models.FloatField(blank=True, db_column='BrutPrime', null=True)),
                ('brutbilan', models.FloatField(blank=True, db_column='BrutBilan', null=True)),
                ('brutprimetotal', models.FloatField(blank=True, db_column='BrutPrimeTotal', null=True)),
                ('montantsoldeconge', models.FloatField(blank=True, db_column='MontantSoldeConge', null=True)),
                ('assiettecnss', models.FloatField(blank=True, db_column='AssietteCNSS', null=True)),
                ('montantassurance', models.FloatField(blank=True, db_column='MontantAssurance', null=True)),
                ('retenuepret1', models.FloatField(blank=True, db_column='RetenuePret1', null=True)),
                ('retenuepret2', models.FloatField(blank=True, db_column='RetenuePret2', null=True)),
                ('retenuepret3', models.FloatField(blank=True, db_column='RetenuePret3', null=True)),
                ('retenuepret4', models.FloatField(blank=True, db_column='RetenuePret4', null=True)),
                ('coutparheure', models.FloatField(blank=True, db_column='CoutParHeure', null=True)),
            ],
            options={
                'db_table': 'Fact_Salaire',
                'managed': False,
            },
        ),
    ]
