# Generated by Django 3.2.13 on 2022-09-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220908_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimEmployee',
            fields=[
                ('id_employee', models.IntegerField(db_column='ID_Employee', primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, db_column='Nom', max_length=255, null=True)),
                ('prenom', models.CharField(blank=True, db_column='Prenom', max_length=255, null=True)),
                ('sexe', models.CharField(blank=True, db_column='Sexe', max_length=1, null=True)),
                ('datenaissance', models.DateField(blank=True, db_column='DateNaissance', null=True)),
                ('lieunaissance', models.CharField(blank=True, db_column='LieuNaissance', max_length=16, null=True)),
                ('adresse', models.CharField(blank=True, db_column='Adresse', max_length=255, null=True)),
                ('ville', models.CharField(blank=True, db_column='Ville', max_length=255, null=True)),
                ('codepostal', models.IntegerField(blank=True, db_column='CodePostal', null=True)),
                ('nbenfant', models.IntegerField(blank=True, db_column='NbEnfant', null=True)),
                ('salairebase', models.FloatField(blank=True, db_column='SalaireBase', null=True)),
                ('banque', models.CharField(blank=True, db_column='Banque', max_length=50, null=True)),
                ('daterecrutement', models.DateField(blank=True, db_column='DateRecrutement', null=True)),
                ('datedebutcontrat', models.DateField(blank=True, db_column='DateDebutContrat', null=True)),
                ('dureecontrat', models.IntegerField(blank=True, db_column='DureeContrat', null=True)),
                ('poste', models.CharField(blank=True, db_column='Poste', max_length=12, null=True)),
                ('montantrend', models.FloatField(blank=True, db_column='MontantRend', null=True)),
                ('noteabsence', models.FloatField(blank=True, db_column='NoteAbsence', null=True)),
                ('nbrabsence', models.IntegerField(blank=True, db_column='NbrAbsence', null=True)),
                ('noteassiduite', models.FloatField(blank=True, db_column='NoteAssiduite', null=True)),
                ('titre', models.CharField(blank=True, db_column='Titre', max_length=1, null=True)),
                ('quitter', models.CharField(blank=True, db_column='Quitter', max_length=1, null=True)),
                ('datequitter', models.DateField(blank=True, db_column='DateQuitter', null=True)),
                ('motifquitter', models.CharField(blank=True, db_column='MotifQuitter', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Dim_Employee',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
